### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by gazza811** [2bite/ARK-SDK#4]
how do i use this please my discord is gazza811#3998

**Comment by vincenthawke** [comment]
Have you learned how to dump the SDK or did you manage to get the proper entity lists by only scanning game memory?

**Comment by Prxdd** [comment]
Can you add my discord @2bite I can give you some money,PrXd#1333

**Comment by Jerem584** [comment]
Guys i posted a "tutorial" on "how-to" use a sdk (based on mine)

https://www.unknowncheats.me/forum/other-fps-games/401611-ark-sdk.html#post2831328

Basicly you just need to have world offset and so you can have entity list and all shits, but 2bite's one is missing actor list

**Comment by Prxdd** [comment]
> Guys i posted a "tutorial" on "how-to" use a sdk (based on mine)
> 
> https://www.unknowncheats.me/forum/other-fps-games/401611-ark-sdk.html#post2831328
> 
> Basicly you just need to have world offset and so you can have entity list and all shits, but 2bite's one is missing actor list

thanks man can u add me discord PrXd#1333

**Comment by vincenthawke** [comment]
Absolute hero, thank you @Jerem584 ! I sent you a PM on UC as well:)
