### ISSUE TITLE
Can u help me

### ISSUE THREAD

**Issue by Prxdd** [2bite/ARK-SDK#5]
can u tall me the GObject,I can't update SDK Or you can upload the latest

**Comment by vincenthawke** [comment]
Have you learned how to dump the SDK or did you manage to get the proper entity lists by only scanning game memory?

**Comment by Prxdd** [comment]
> 您是否了解了如何转储SDK或仅通过扫描游戏内存就设法获得了正确的实体列表？



> Have you learned how to dump the SDK or did you manage to get the proper entity lists by only scanning game memory?

i cant dump sdk,but ican use ce to find any address,u can add me discord PrXd#1333
