### ISSUE TITLE
What tool?

### ISSUE THREAD

**Issue by Wearwolfy** [2bite/ARK-SDK#6]
What tool are you using to generate those sdk's? Thanks in Advance!

**Comment by Jerem584** [comment]
We use https://github.com/KN4CK3R/UnrealEngineSDKGenerator/network/members

**Comment by amcgregor** [comment]
> Due to legal reasons the UnrealEngineSDKGenerator isn't available here anymore.

The fact that the original repository has been utterly scrubbed is worrying. Mildly curious as to the history of that.

**Comment by amcgregor** [comment]
Fair enough.

There are forks that still contain the code, but of course, it's absolutely dubious to make use of them with the warning on the original repo in place.
